aluno = ['Pedro',
           'Borges',
           'Pedro H',
           'vinicius',
           'Felipe Morente',
           'João',
           'Felipe henrique',
           'Matheus Monteiro',
           'Diego',
           'Raissa',
           'Ricardo',
           'Luiza',
           'Beatriz',
           'Vanessa',
           'Amanda',
           'Isabela',
           'kasly',
           'Jhonatan',
           'Henrique',
           'Kaique',
           'Taielan',
           'Matheus Monteiro',
           'Guilherme pereira',
           'Flavia',
           'Ramon',
           'Matheus Braga',
           'Beatriz Cruz',
           'Matheus Silveira',
           'João Pedro']

for i in range(0,len(aluno)):
    print(f'0 {i + 1}º nome da lista é: {aluno[i]}')